" Generated by vim-plug
" Wed 15 Feb 2017 10:38:57 PM PST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ctrlp-funky'].commit = '921e8f8'
silent! let g:plugs['ctrlp.vim'].commit = '564176f'
silent! let g:plugs['deoplete-jedi'].commit = '6240de8'
silent! let g:plugs['deoplete.nvim'].commit = 'eb65320'
silent! let g:plugs['neco-vim'].commit = 'd28e1ea'
silent! let g:plugs['neomake'].commit = 'c34ac13'
silent! let g:plugs['tagbar'].commit = '9d051c1'
silent! let g:plugs['vim-autopep8'].commit = 'c5e62f0'
silent! let g:plugs['vim-commentary'].commit = '73e0d9a'
silent! let g:plugs['vim-markdown-preview'].commit = 'e4b8b9c'
silent! let g:plugs['vim-operator-surround'].commit = '521afdc'
silent! let g:plugs['vim-operator-user'].commit = 'c3dfd41'
silent! let g:plugs['vim-pencil'].commit = '6d01570'
silent! let g:plugs['vim-textobj-between'].commit = 'b4986c1'
silent! let g:plugs['vim-textobj-comment'].commit = '58ae457'
silent! let g:plugs['vim-textobj-indent'].commit = 'deb7686'
silent! let g:plugs['vim-textobj-sentence'].commit = '81513f1'
silent! let g:plugs['vim-textobj-user'].commit = 'a305416'
silent! let g:plugs['vimtex'].commit = 'de61b31'

PlugUpdate!

