return {
  ensure_installed = {
    "bash",
    "c",
    "cpp",
    "css",
    "csv",
    "desktop",
    "diff",
    "fish",
    "git_rebase",
    "gitignore",
    "haskell",
    "html",
    "json",
    "julia",
    "latex",
    "lua",
    "markdown_inline",
    "matlab",
    "ocaml",
    "ocaml_interface",
    "python",
    "regex",
    "rust",
    "ssh_config",
    "toml",
    "typescript",
    "vim",
    "vimdoc",
    "xml",
    "yaml"
  },
  sync_install = false,
  highlight = { enable = true },
  indent = { enable = true },
}
