vim.api.nvim_set_keymap("n", "<leader>p", ":Telescope<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>f", ":Telescope find_files theme=get_dropdown previewer=false<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>g", ":Telescope git_files theme=get_dropdown previewer=false<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>b", ":Telescope buffers theme=get_dropdown previewer=false<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>h", ":Telescope help_tags<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>i", ":Telescope frecency theme=get_dropdown previewer=false<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>l", ":Telescope diagnostics bufnr=0 theme=get_dropdown<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>e", ":Telescope file_browser<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>r", ":Telescope live_grep<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>m", ":Telescope commands theme=get_dropdown<CR>", { noremap = true })
