#!/usr/bin/env python
import subprocess
import sys
import re

# Set up the environment
fname = sys.argv[1]
curr_dir = sys.argv[2]
try:
    ext = re.search(r'(\.[\w]+\b)', fname).groups()[0]
except:
    sys.exit()

# Execute the file. Automatically chooses the correct interpreter and/or compiler.
interpreters = {
    '.py': '$HOME/anaconda3/bin/python ',
    '.jl': '$HOME/julia/bin/julia '
}

if ext in interpreters:
    run_script = interpreters[ext] + fname + '\n'
elif ext == '.rs':
    run_script = 'cargo run\n'

# Create a shell script in the /tmp directory
with open('/tmp/run', 'w') as cmd:
    cmd.write('#!/bin/bash\n')
    cmd.write('cd ' + curr_dir + '\n')
    cmd.writelines(run_script)

# Execute the script through a python wrapper script
subprocess.Popen(['chmod', '+x', '/tmp/run'])
subprocess.Popen(['x-terminal-emulator', '-e', '$HOME/.vim/plugin/wrap'])
