#!/usr/bin/env python
import subprocess
import sys
import re
import os

# Set up the environment
fname = sys.argv[1]
ext = re.search(r'(\.[\w]+\b)', fname).groups()[0]
xterm_title = 'Execute: ' + fname

# Execute the file. Automatically chooses the correct interpreter and/or compiler.
interpreters = {
    '.py': '$HOME/anaconda3/bin/python ',
    '.jl': '$HOME/julia/bin/julia '
}

if ext in interpreters:
    command = interpreters[ext] + fname + ';'
elif ext == '.rs':
    command = 'cargo run;'

# Message to display at the end of the program
command += 'echo \'\n---------------------------\nPress RETURN to exit\';'
command += 'read -p \'\''

subprocess.Popen(['xterm', '-T', xterm_title, '-e', command])
