#!/usr/bin/env python
from __future__ import print_function
import subprocess
import sys


def exit():
    print('\n------------------------------')
    print('\nPress RETURN to exit')
    input()


try:
    subprocess.Popen(['/tmp/run']).wait()
except:
    exit()
    sys.exit()

exit()
