#!/usr/bin/python3
import subprocess


def exit():
    print('\n')
    print('------------------------------')
    print('')
    print('Press RETURN to exit')
    input()


try:
    subprocess.Popen(['/tmp/run']).wait()
    exit()
except:
    exit()
