#!/usr/bin/env python
import subprocess
import sys
import re
import os


def find_proj_root():
    proj_root = curr_dir
    while True:
        if os.path.isdir(proj_root + '/.git'):
            break
        else:
            # Search for the .git folder up the directory tree
            proj_root = ''.join(re.findall(r'(\/[\w]+)', proj_root)[:-1])
            if len(proj_root) == 0:
                raise Exception
    return proj_root


# Set up the environment
envs = {
    '.py': '/usr/bin/python3 ',
    '.jl': '/usr/bin/env julia '
}

fname = sys.argv[1]
curr_dir = sys.argv[2]

# Filter file types by extension
try:
    ext = re.search(r'(\.[\w]+\b)', fname).groups()[0]
except:
    sys.exit()

# Find the interpreter config file in the current directory. If none was found,
#  proceed to search for the file in the project root dir. Fall back to
#  the default interpreter if one is not found.
#  The interpreter config file should only contain one line--the path to the
#  interpreter. The interpreter config file is optional and only works for
#  interpreted/JIT compiled languages.
if ext in envs:
    if os.path.isfile(curr_dir + '/.env'):
        p = open(curr_dir + '/.env')
        env = p.read()[:-1] + ' '     # When reading files '\n' is appended
        p.close()
    else:
        try:
            proj_root = find_proj_root()
            if os.path.isfile(proj_root + '/.env'):
                p = open(proj_root + '/.env')
                env = p.read()[:-1] + ' '
                p.close()
            else:
                env = envs[ext]
        except:
            env = envs[ext]

# Choose the right runtime/compiler
if ext in envs:
    run_script = env + fname + '\n'
elif ext == '.rs':
    run_script = 'cargo run\n'

# Create a shell script in the /tmp directory
with open('/tmp/run', 'w') as cmd:
    cmd.write('#!/bin/bash\n')
    cmd.write('cd ' + curr_dir + '\n')
    cmd.writelines(run_script)
subprocess.Popen(['chmod', '+x', '/tmp/run']).wait()

# Execute the script through a wrapper script
exttools_dir = os.getenv('HOME') + '/.vim/plugin/external-tools.vim/'
term_title = 'Execute: ' + fname
subprocess.Popen([exttools_dir + 'open-term', term_title])
